config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :articles

  validates :password, presence: true, length: { minimum: 6 }, if: "password_digest.nil?"
  validates :password, length: { minimum: 6 }, allow_blank: true
  validates :email,
             presence: true,
             uniqueness: { case_sensitive: false },
             length: { minimum: 3, maximum: 254 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag "/assets/stylesheets/application" %>
    <%= stylesheet_link_tag "/assets/stylesheets/about" %>
    <%= stylesheet_link_tag "/assets/stylesheets/index" %>
    <%= stylesheet_link_tag "/assets/stylesheets/devise" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
    <div id="current-user">
      Signed in as: <strong><%= current_user.email %></strong> |
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
    <div id="sign-in">
      <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
      <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
    </div>
    <% end %>
    </div>
    <div class="container">
        <ul class="nav nav-tabs">
          <li><%= link_to "Home", welcome_index_path %></li>
          <li><%= link_to "About", welcome_about_path %></li>
        </ul>
    </div>
    <p class="notice"><%= notice%></p>
    <p class="alert"><%= alert %><p/>

    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/about.html.erb
<div class="container">
     <h1 class="jumbotron">
       About Me
     </h1>
     <div class="row">
       <div class="col-md-7">
         <a href="#">
           <img class="img-fluid rounded mb-3 mb-md-0" src="http://placehold.it/500x300" alt="">
         </a>
       </div>
       <div class="col-md-5">
         <p>Labore, voluptates totam at aut nemo deserunt rem magni pariatur quos perspiciatis atque eveniet unde. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi bibendum cursus purus ac feugiat. Vestibulum viverra lectus non nunc consequat lobortis. Donec vel neque ac est rutrum mollis. Sed ac orci nunc. Cras nisi arcu, lacinia vitae suscipit hendrerit, accumsan in elit. Aliquam vitae pretium massa. Mauris gravida urna vitae ipsum tristique, eget pellentesque justo gravida. Suspendisse potenti. Phasellus pellentesque nunc mauris, ac volutpat sem ullamcorper ac. Ut sagittis libero euismod enim imperdiet ullamcorper. Pellentesque ultrices nisl ut felis ullamcorper, eu dictum sem pretium. Nullam condimentum erat et justo euismod, eget consequat nisi pharetra. Fusce rutrum cursus pharetra.</p>
       </div>
     </div>

   <footer class="py-5 bg-dark" id="about-footer">
     <div class="container">
       <p class="m-0 text-center text-white">Copyright &copy; Alpha Blog 2018</p>
     </div>
   </footer>

app/views/welcome/index.html.erb
<div class="container">
     <h1 class="jumbotron">
       Alpha Blog
     </h1>
     <div class="row">
       <div class="col-md-7">
         <a href="#">
           <img class="img-fluid rounded mb-3 mb-md-0" src="http://placehold.it/500x300" alt="">
         </a>
       </div>
       <div class="col-md-5">
         <h3>Post One</h3>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium veniam exercitationem expedita laborum at voluptate. Labore, voluptates totam at aut nemo deserunt rem magni pariatur quos perspiciatis atque eveniet unde.</p>
         <a class="btn btn-primary" href="#">View post</a>
       </div>
     </div>
     <hr>
     <div class="row">
       <div class="col-md-7">
         <a href="#">
           <img class="img-fluid rounded mb-3 mb-md-0" src="http://placehold.it/500x300" alt="">
         </a>
       </div>
       <div class="col-md-5">
         <h3>Post Two</h3>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, odit velit cumque vero doloremque repellendus distinctio maiores rem expedita a nam vitae modi quidem similique ducimus! Velit, esse totam tempore.</p>
         <a class="btn btn-primary" href="#">View post</a>
       </div>
     </div>
     <hr>
     <div class="row">
       <div class="col-md-7">
         <a href="#">
           <img class="img-fluid rounded mb-3 mb-md-0" src="http://placehold.it/500x300" alt="">
         </a>
       </div>
       <div class="col-md-5">
         <h3>Post Three</h3>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, temporibus, dolores, at, praesentium ut unde repudiandae voluptatum sit ab debitis suscipit fugiat natus velit excepturi amet commodi deleniti alias possimus!</p>
         <a class="btn btn-primary" href="#">View post</a>
       </div>
     </div>
     <hr>
     <div class="row">
       <div class="col-md-7">
         <a href="#">
           <img class="img-fluid rounded mb-3 mb-md-0" src="http://placehold.it/500x300" alt="">
         </a>
       </div>
       <div class="col-md-5">
         <h3>Post Four</h3>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo, quidem, consectetur, officia rem officiis illum aliquam perspiciatis aspernatur quod modi hic nemo qui soluta aut eius fugit quam in suscipit?</p>
         <a class="btn btn-primary" href="#">View post</a>
       </div>
     </div>

     <hr>
     <ul class="pagination justify-content-center">
       <li class="page-item">
         <a class="page-link" href="#" aria-label="Previous">
           <span aria-hidden="true">&laquo;</span>
           <span class="sr-only">Previous</span>
         </a>
       </li>
       <li class="page-item">
         <a class="page-link" href="#">1</a>
       </li>
       <li class="page-item">
         <a class="page-link" href="#">2</a>
       </li>
       <li class="page-item">
         <a class="page-link" href="#">3</a>
       </li>
       <li class="page-item">
         <a class="page-link" href="#" aria-label="Next">
           <span aria-hidden="true">&raquo;</span>
           <span class="sr-only">Next</span>
         </a>
       </li>
     </ul>
   </div>

   <footer class="py-5 bg-dark">
     <div class="container">
       <p class="m-0 text-center text-white">Copyright &copy; Alpha Blog 2018</p>
     </div>
   </footer>